 export const cardsElements = [
 {
    id: 0,
    paragrafi1: "Ne dyqan dhe online",
    header1: "Ore inteligjente XIAOMI Redmi Ora 3 aktive, e zeze",
    image: "https://assets.mmsrg.com/isr/166325/c1/-/ASSET_MMS_107996820?x=320&y=320&format=jpg&quality=80&sp=yes&strip=yes&trim&ex=320&ey=320&align=center&resizesource&unsharp=1.5x1+0.7+0.02&cox=0&coy=0&cdx=320&cdy=320",
    paragrafi2: "Lloji i pajisjes:",
    header2: "SMARTWATCH",
    paragrafi3: "Sisteme operative te pajtueshme:",
    header3: "-",
    paragrafi3: "Sensori i rrahjeve te zemres:",
    header4: "po",
    paragrafi4: "etegjatesia e baterise:",
    header5: "288 ore",
    paragrafi5: "32",
    header6: "E rekomanduar 39.99 €",
    header7: "34,99 €",
    link1: "Informacion mbi: Financimi, Cmimi, Sasia, Koha e dorezimit dhe Marrja",
    paragrafi6: "Eko-kontributi i TVSH dhe WEEE i perfshire",
    header8: {header: "Ofrohet dorezimi", span: "+2,99 €"},
    paragrafi7: "Dorezimi i parashikuar 21.08.2024 - 23.08.2024(Ne shporte, shkruani kodin postar dhe do te keni nje date me te sakte)",
    header9: "Koleksioni FALAS ne dyqan",
    paragrafi8: {paragraf: "Kontrolloni koleksionin ne dyqan", span: "Zgjidh Dyqanin >"},
    butoni: "Shto ne Shporte",

},
 {
    id: 1,
    paragrafi1: "Ne dyqan dhe online",
    header1: "Ore inteligjente XIAOMI Redmi Ora 3 aktive, e zeze",
    image: "https://assets.mmsrg.com/isr/166325/c1/-/ASSET_MMS_107996820?x=320&y=320&format=jpg&quality=80&sp=yes&strip=yes&trim&ex=320&ey=320&align=center&resizesource&unsharp=1.5x1+0.7+0.02&cox=0&coy=0&cdx=320&cdy=320",
    paragrafi2: "Lloji i pajisjes:",
    header2: "SMARTWATCH",
    paragrafi3: "Sisteme operative te pajtueshme:",
    header3: "-",
    paragrafi3: "Sensori i rrahjeve te zemres:",
    header4: "po",
    paragrafi4: "etegjatesia e baterise:",
    header5: "288 ore",
    paragrafi5: "32",
    header6: "E rekomanduar 39.99 €",
    header7: "34,99 €",
    link1: "Informacion mbi: Financimi, Cmimi, Sasia, Koha e dorezimit dhe Marrja",
    paragrafi6: "Eko-kontributi i TVSH dhe WEEE i perfshire",
    header8: {header: "Ofrohet dorezimi", span: "+2,99 €"},
    paragrafi7: "Dorezimi i parashikuar 21.08.2024 - 23.08.2024(Ne shporte, shkruani kodin postar dhe do te keni nje date me te sakte)",
    header9: "Koleksioni FALAS ne dyqan",
    paragrafi8: {paragraf: "Kontrolloni koleksionin ne dyqan", span: "Zgjidh Dyqanin >"},
    butoni: "Shto ne Shporte",

},
 {
    id: 2,
    paragrafi1: "Ne dyqan dhe online",
    header1: "Ore inteligjente XIAOMI Redmi Ora 3 aktive, e zeze",
    image: "https://assets.mmsrg.com/isr/166325/c1/-/ASSET_MMS_107996820?x=320&y=320&format=jpg&quality=80&sp=yes&strip=yes&trim&ex=320&ey=320&align=center&resizesource&unsharp=1.5x1+0.7+0.02&cox=0&coy=0&cdx=320&cdy=320",
    paragrafi2: "Lloji i pajisjes:",
    header2: "SMARTWATCH",
    paragrafi3: "Sisteme operative te pajtueshme:",
    header3: "-",
    paragrafi3: "Sensori i rrahjeve te zemres:",
    header4: "po",
    paragrafi4: "etegjatesia e baterise:",
    header5: "288 ore",
    paragrafi5: "32",
    header6: "E rekomanduar 39.99 €",
    header7: "34,99 €",
    link1: "Informacion mbi: Financimi, Cmimi, Sasia, Koha e dorezimit dhe Marrja",
    paragrafi6: "Eko-kontributi i TVSH dhe WEEE i perfshire",
    header8: {header: "Ofrohet dorezimi", span: "+2,99 €"},
    paragrafi7: "Dorezimi i parashikuar 21.08.2024 - 23.08.2024(Ne shporte, shkruani kodin postar dhe do te keni nje date me te sakte)",
    header9: "Koleksioni FALAS ne dyqan",
    paragrafi8: {paragraf: "Kontrolloni koleksionin ne dyqan", span: "Zgjidh Dyqanin >"},
    butoni: "Shto ne Shporte",

},
 {
    id: 3,
    paragrafi1: "Ne dyqan dhe online",
    header1: "Ore inteligjente XIAOMI Redmi Ora 3 aktive, e zeze",
    image: "https://assets.mmsrg.com/isr/166325/c1/-/ASSET_MMS_107996820?x=320&y=320&format=jpg&quality=80&sp=yes&strip=yes&trim&ex=320&ey=320&align=center&resizesource&unsharp=1.5x1+0.7+0.02&cox=0&coy=0&cdx=320&cdy=320",
    paragrafi2: "Lloji i pajisjes:",
    header2: "SMARTWATCH",
    paragrafi3: "Sisteme operative te pajtueshme:",
    header3: "-",
    paragrafi3: "Sensori i rrahjeve te zemres:",
    header4: "po",
    paragrafi4: "etegjatesia e baterise:",
    header5: "288 ore",
    paragrafi5: "32",
    header6: "E rekomanduar 39.99 €",
    header7: "34,99 €",
    link1: "Informacion mbi: Financimi, Cmimi, Sasia, Koha e dorezimit dhe Marrja",
    paragrafi6: "Eko-kontributi i TVSH dhe WEEE i perfshire",
    header8: {header: "Ofrohet dorezimi", span: "+2,99 €"},
    paragrafi7: "Dorezimi i parashikuar 21.08.2024 - 23.08.2024(Ne shporte, shkruani kodin postar dhe do te keni nje date me te sakte)",
    header9: "Koleksioni FALAS ne dyqan",
    paragrafi8: {paragraf: "Kontrolloni koleksionin ne dyqan", span: "Zgjidh Dyqanin >"},
    butoni: "Shto ne Shporte",

},
 {
    id: 4,
    paragrafi1: "Ne dyqan dhe online",
    header1: "Ore inteligjente XIAOMI Redmi Ora 3 aktive, e zeze",
    image: "https://assets.mmsrg.com/isr/166325/c1/-/ASSET_MMS_107996820?x=320&y=320&format=jpg&quality=80&sp=yes&strip=yes&trim&ex=320&ey=320&align=center&resizesource&unsharp=1.5x1+0.7+0.02&cox=0&coy=0&cdx=320&cdy=320",
    paragrafi2: "Lloji i pajisjes:",
    header2: "SMARTWATCH",
    paragrafi3: "Sisteme operative te pajtueshme:",
    header3: "-",
    paragrafi3: "Sensori i rrahjeve te zemres:",
    header4: "po",
    paragrafi4: "etegjatesia e baterise:",
    header5: "288 ore",
    paragrafi5: "32",
    header6: "E rekomanduar 39.99 €",
    header7: "34,99 €",
    link1: "Informacion mbi: Financimi, Cmimi, Sasia, Koha e dorezimit dhe Marrja",
    paragrafi6: "Eko-kontributi i TVSH dhe WEEE i perfshire",
    header8: {header: "Ofrohet dorezimi", span: "+2,99 €"},
    paragrafi7: "Dorezimi i parashikuar 21.08.2024 - 23.08.2024(Ne shporte, shkruani kodin postar dhe do te keni nje date me te sakte)",
    header9: "Koleksioni FALAS ne dyqan",
    paragrafi8: {paragraf: "Kontrolloni koleksionin ne dyqan", span: "Zgjidh Dyqanin >"},
    butoni: "Shto ne Shporte",

},
 {
    id: 5,
    paragrafi1: "Ne dyqan dhe online",
    header1: "Ore inteligjente XIAOMI Redmi Ora 3 aktive, e zeze",
    image: "https://assets.mmsrg.com/isr/166325/c1/-/ASSET_MMS_107996820?x=320&y=320&format=jpg&quality=80&sp=yes&strip=yes&trim&ex=320&ey=320&align=center&resizesource&unsharp=1.5x1+0.7+0.02&cox=0&coy=0&cdx=320&cdy=320",
    paragrafi2: "Lloji i pajisjes:",
    header2: "SMARTWATCH",
    paragrafi3: "Sisteme operative te pajtueshme:",
    header3: "-",
    paragrafi3: "Sensori i rrahjeve te zemres:",
    header4: "po",
    paragrafi4: "etegjatesia e baterise:",
    header5: "288 ore",
    paragrafi5: "32",
    header6: "E rekomanduar 39.99 €",
    header7: "34,99 €",
    link1: "Informacion mbi: Financimi, Cmimi, Sasia, Koha e dorezimit dhe Marrja",
    paragrafi6: "Eko-kontributi i TVSH dhe WEEE i perfshire",
    header8: {header: "Ofrohet dorezimi", span: "+2,99 €"},
    paragrafi7: "Dorezimi i parashikuar 21.08.2024 - 23.08.2024(Ne shporte, shkruani kodin postar dhe do te keni nje date me te sakte)",
    header9: "Koleksioni FALAS ne dyqan",
    paragrafi8: {paragraf: "Kontrolloni koleksionin ne dyqan", span: "Zgjidh Dyqanin >"},
    butoni: "Shto ne Shporte",

},
 {
    id: 6,
    paragrafi1: "Ne dyqan dhe online",
    header1: "Ore inteligjente XIAOMI Redmi Ora 3 aktive, e zeze",
    image: "https://assets.mmsrg.com/isr/166325/c1/-/ASSET_MMS_107996820?x=320&y=320&format=jpg&quality=80&sp=yes&strip=yes&trim&ex=320&ey=320&align=center&resizesource&unsharp=1.5x1+0.7+0.02&cox=0&coy=0&cdx=320&cdy=320",
    paragrafi2: "Lloji i pajisjes:",
    header2: "SMARTWATCH",
    paragrafi3: "Sisteme operative te pajtueshme:",
    header3: "-",
    paragrafi3: "Sensori i rrahjeve te zemres:",
    header4: "po",
    paragrafi4: "etegjatesia e baterise:",
    header5: "288 ore",
    paragrafi5: "32",
    header6: "E rekomanduar 39.99 €",
    header7: "34,99 €",
    link1: "Informacion mbi: Financimi, Cmimi, Sasia, Koha e dorezimit dhe Marrja",
    paragrafi6: "Eko-kontributi i TVSH dhe WEEE i perfshire",
    header8: {header: "Ofrohet dorezimi", span: "+2,99 €"},
    paragrafi7: "Dorezimi i parashikuar 21.08.2024 - 23.08.2024(Ne shporte, shkruani kodin postar dhe do te keni nje date me te sakte)",
    header9: "Koleksioni FALAS ne dyqan",
    paragrafi8: {paragraf: "Kontrolloni koleksionin ne dyqan", span: "Zgjidh Dyqanin >"},
    butoni: "Shto ne Shporte",

}
];