 export const cardsElements = [
 {
    id: 0,
    paragrafi1: "Ne dyqan dhe online",
    header1: "Ore inteligjente XIAOMI Redmi Ora 3 aktive, e zeze",
    image: "https://assets.mmsrg.com/isr/166325/c1/-/ASSET_MMS_107996820?x=320&y=320&format=jpg&quality=80&sp=yes&strip=yes&trim&ex=320&ey=320&align=center&resizesource&unsharp=1.5x1+0.7+0.02&cox=0&coy=0&cdx=320&cdy=320",
    paragrafi2: "Lloji i pajisjes:",
    header2: "SMARTWATCH",
    paragrafi3: "Sisteme operative te pajtueshme:",
    header3: "-",
    paragrafi3: "Sensori i rrahjeve te zemres:",
    header4: "po",
    paragrafi4: "etegjatesia e baterise:",
    header5: "288 ore",
    paragrafi5: "32",
    header6: "E rekomanduar 39.99 €",
    header7: "34,99 €",
    link1: "Informacion mbi: Financimi, Cmimi, Sasia, Koha e dorezimit dhe Marrja",
    paragrafi6: "Eko-kontributi i TVSH dhe WEEE i perfshire",
    header8: {header: "Ofrohet dorezimi", span: "+2,99 €"},
    paragrafi7: "Dorezimi i parashikuar 21.08.2024 - 23.08.2024(Ne shporte, shkruani kodin postar dhe do te keni nje date me te sakte)",
    header9: "Koleksioni FALAS ne dyqan",
    paragrafi8: {paragraf: "Kontrolloni koleksionin ne dyqan", span: "Zgjidh Dyqanin >"},
    butoni: "Shto ne Shporte",

},
 {
    id: 1,
    paragrafi1: "Ne dyqan dhe online",
    header1: "Ore inteligjente XIAOMI Redmi Ora 3 aktive, e zeze",
    image: "https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/watch-card-40-s11-202509_GEO_US?wid=680&hei=528&fmt=jpeg&qlt=90&.v=RGt6QnVpU0piVDZnRHZnWmNNbHB2N1kwNlR4L1oxcmNLdEMxb09HZ1RqYTJjSW42RjNkUmxsaVhqRzVyUDdYaTE1UUxLT2t0cW42N3FvQzVqaGhrVVM3ZXVHSjh6dHVIQnNuWHRNL1lHcFYrYWpGdS9XeFgvbS9ITnNYOEhYaG4",
    paragrafi2: "Lloji i pajisjes:",
    header2: "SMARTWATCH",
    paragrafi3: "Sisteme operative te pajtueshme:",
    header3: "-",
    paragrafi3: "Sensori i rrahjeve te zemres:",
    header4: "po",
    paragrafi4: "etegjatesia e baterise:",
    header5: "288 ore",
    paragrafi5: "32",
    header6: "E rekomanduar 39.99 €",
    header7: "34,99 €",
    link1: "Informacion mbi: Financimi, Cmimi, Sasia, Koha e dorezimit dhe Marrja",
    paragrafi6: "Eko-kontributi i TVSH dhe WEEE i perfshire",
    header8: {header: "Ofrohet dorezimi", span: "+2,99 €"},
    paragrafi7: "Dorezimi i parashikuar 21.08.2024 - 23.08.2024(Ne shporte, shkruani kodin postar dhe do te keni nje date me te sakte)",
    header9: "Koleksioni FALAS ne dyqan",
    paragrafi8: {paragraf: "Kontrolloni koleksionin ne dyqan", span: "Zgjidh Dyqanin >"},
    butoni: "Shto ne Shporte",

},
 {
    id: 2,
    paragrafi1: "Ne dyqan dhe online",
    header1: "Ore inteligjente XIAOMI Redmi Ora 3 aktive, e zeze",
    image: "https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/watch-card-40-se3-202509?wid=680&hei=528&fmt=p-jpg&qlt=95&.v=dFQyNjEycitpbFBFNXA5RHpaQjc1bFpSbk5JVjhoV0ZGWlRwRHJpZ2pjazgycjlDNGdlREhyeERCVjM1SXkycjBvTHRTQjdCWE9PcW9rdVY3NVlSRExzQTYyYlNCZE1Hd3p6QUhoVmMwWms",
    paragrafi2: "Lloji i pajisjes:",
    header2: "SMARTWATCH",
    paragrafi3: "Sisteme operative te pajtueshme:",
    header3: "-",
    paragrafi3: "Sensori i rrahjeve te zemres:",
    header4: "po",
    paragrafi4: "etegjatesia e baterise:",
    header5: "288 ore",
    paragrafi5: "32",
    header6: "E rekomanduar 39.99 €",
    header7: "34,99 €",
    link1: "Informacion mbi: Financimi, Cmimi, Sasia, Koha e dorezimit dhe Marrja",
    paragrafi6: "Eko-kontributi i TVSH dhe WEEE i perfshire",
    header8: {header: "Ofrohet dorezimi", span: "+2,99 €"},
    paragrafi7: "Dorezimi i parashikuar 21.08.2024 - 23.08.2024(Ne shporte, shkruani kodin postar dhe do te keni nje date me te sakte)",
    header9: "Koleksioni FALAS ne dyqan",
    paragrafi8: {paragraf: "Kontrolloni koleksionin ne dyqan", span: "Zgjidh Dyqanin >"},
    butoni: "Shto ne Shporte",

},
 {
    id: 3,
    paragrafi1: "Ne dyqan dhe online",
    header1: "Ore inteligjente XIAOMI Redmi Ora 3 aktive, e zeze",
    image: "https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/watch-card-40-ultra3-202509_GEO_US?wid=680&hei=528&fmt=p-jpg&qlt=95&.v=Yldjd2t3Ymo3YVZBc2hwblI4VFkzckh2d2I2QWRTY0NRMFJRd2UzeExSczBUZG9jeU40eXVpQXBKTXpRY2Q4dVhHUkcvNmtpMGxDZTE1ejhaNlcyMHp1MnZVNkVGSEJOV2tCeXV3UExBSWY1R0pqQXNoaUNETnNuWkgwY0hpcFg",
    paragrafi2: "Lloji i pajisjes:",
    header2: "SMARTWATCH",
    paragrafi3: "Sisteme operative te pajtueshme:",
    header3: "-",
    paragrafi3: "Sensori i rrahjeve te zemres:",
    header4: "po",
    paragrafi4: "etegjatesia e baterise:",
    header5: "288 ore",
    paragrafi5: "32",
    header6: "E rekomanduar 39.99 €",
    header7: "34,99 €",
    link1: "Informacion mbi: Financimi, Cmimi, Sasia, Koha e dorezimit dhe Marrja",
    paragrafi6: "Eko-kontributi i TVSH dhe WEEE i perfshire",
    header8: {header: "Ofrohet dorezimi", span: "+2,99 €"},
    paragrafi7: "Dorezimi i parashikuar 21.08.2024 - 23.08.2024(Ne shporte, shkruani kodin postar dhe do te keni nje date me te sakte)",
    header9: "Koleksioni FALAS ne dyqan",
    paragrafi8: {paragraf: "Kontrolloni koleksionin ne dyqan", span: "Zgjidh Dyqanin >"},
    butoni: "Shto ne Shporte",

},
 {
    id: 4,
    paragrafi1: "Ne dyqan dhe online",
    header1: "Ore inteligjente XIAOMI Redmi Ora 3 aktive, e zeze",
    image: "https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/watch-card-40-hermes-202509?wid=680&hei=528&fmt=p-jpg&qlt=95&.v=Ly93VWF6a1dGOWJLL3RMM0s0eGZ6bmNVK3pMVFUxQXlhSWdsS1dpNlR1MUMxQXc4S3pBZE5lUDJlTzVYSUYydFMwV0hhcmdVdXZzZ1NwTlFUaEgwTHpjcGJkYllSSE5oejdnSXFOU0tqU0E",
    paragrafi2: "Lloji i pajisjes:",
    header2: "SMARTWATCH",
    paragrafi3: "Sisteme operative te pajtueshme:",
    header3: "-",
    paragrafi3: "Sensori i rrahjeve te zemres:",
    header4: "po",
    paragrafi4: "etegjatesia e baterise:",
    header5: "288 ore",
    paragrafi5: "32",
    header6: "E rekomanduar 39.99 €",
    header7: "34,99 €",
    link1: "Informacion mbi: Financimi, Cmimi, Sasia, Koha e dorezimit dhe Marrja",
    paragrafi6: "Eko-kontributi i TVSH dhe WEEE i perfshire",
    header8: {header: "Ofrohet dorezimi", span: "+2,99 €"},
    paragrafi7: "Dorezimi i parashikuar 21.08.2024 - 23.08.2024(Ne shporte, shkruani kodin postar dhe do te keni nje date me te sakte)",
    header9: "Koleksioni FALAS ne dyqan",
    paragrafi8: {paragraf: "Kontrolloni koleksionin ne dyqan", span: "Zgjidh Dyqanin >"},
    butoni: "Shto ne Shporte",

},
 {
    id: 5,
    paragrafi1: "Ne dyqan dhe online",
    header1: "Ore inteligjente XIAOMI Redmi Ora 3 aktive, e zeze",
    image: "https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/watch-card-40-hermes-ultra-202509_GEO_US?wid=680&hei=528&fmt=jpeg&qlt=90&.v=Ly93VWF6a1dGOWJLL3RMM0s0eGZ6bGptdm4xZHhxZWZzUlhoOU9Da0hNNVU4aHdGN0xlWGtoZjR6dnFUWE9VVTV0VzZXemQ1ZkRzK0p5ZFBxZERkQ3o2K3c3eDN1QlVKV09nQzhyNmV5TTNjeFVjd0E0NEk3ZEplNUNxd0pRazY",
    paragrafi2: "Lloji i pajisjes:",
    header2: "SMARTWATCH",
    paragrafi3: "Sisteme operative te pajtueshme:",
    header3: "-",
    paragrafi3: "Sensori i rrahjeve te zemres:",
    header4: "po",
    paragrafi4: "etegjatesia e baterise:",
    header5: "288 ore",
    paragrafi5: "32",
    header6: "E rekomanduar 39.99 €",
    header7: "34,99 €",
    link1: "Informacion mbi: Financimi, Cmimi, Sasia, Koha e dorezimit dhe Marrja",
    paragrafi6: "Eko-kontributi i TVSH dhe WEEE i perfshire",
    header8: {header: "Ofrohet dorezimi", span: "+2,99 €"},
    paragrafi7: "Dorezimi i parashikuar 21.08.2024 - 23.08.2024(Ne shporte, shkruani kodin postar dhe do te keni nje date me te sakte)",
    header9: "Koleksioni FALAS ne dyqan",
    paragrafi8: {paragraf: "Kontrolloni koleksionin ne dyqan", span: "Zgjidh Dyqanin >"},
    butoni: "Shto ne Shporte",

},
 {
    id: 6,
    paragrafi1: "Ne dyqan dhe online",
    header1: "Ore inteligjente XIAOMI Redmi Ora 3 aktive, e zeze",
    image: "https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/watch-hermes-ultra-digitalmat-gallery-1-202509?wid=728&hei=666&fmt=png-alpha&.v=OFlDdDc4cmVqVndMYTR6RzI0QWt3QWExdks3UGdOVGViclAzTTVPNWtleGpVcEVzSFZMUjZpQjFxdHIyUk1tVmVkZGptNUJaWitJZ3gyOURkSTlZQ3ROL1VCcUxMZGhIeWpHS1Y3Y0ZmQnBBYk1TOTVEbm5DeGFHUUxieERHTVg",
    paragrafi2: "Lloji i pajisjes:",
    header2: "SMARTWATCH",
    paragrafi3: "Sisteme operative te pajtueshme:",
    header3: "-",
    paragrafi3: "Sensori i rrahjeve te zemres:",
    header4: "po",
    paragrafi4: "etegjatesia e baterise:",
    header5: "288 ore",
    paragrafi5: "32",
    header6: "E rekomanduar 39.99 €",
    header7: "34,99 €",
    link1: "Informacion mbi: Financimi, Cmimi, Sasia, Koha e dorezimit dhe Marrja",
    paragrafi6: "Eko-kontributi i TVSH dhe WEEE i perfshire",
    header8: {header: "Ofrohet dorezimi", span: "+2,99 €"},
    paragrafi7: "Dorezimi i parashikuar 21.08.2024 - 23.08.2024(Ne shporte, shkruani kodin postar dhe do te keni nje date me te sakte)",
    header9: "Koleksioni FALAS ne dyqan",
    paragrafi8: {paragraf: "Kontrolloni koleksionin ne dyqan", span: "Zgjidh Dyqanin >"},
    butoni: "Shto ne Shporte",

},
 {
    id: 7,
    paragrafi1: "Ne dyqan dhe online",
    header1: "Ore inteligjente XIAOMI Redmi Ora 3 aktive, e zeze",
    image: "https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/watch-hermes-ultra-digitalmat-gallery-7-202509_GEO_US?wid=728&hei=666&fmt=png-alpha&.v=OFlDdDc4cmVqVndMYTR6RzI0QWt3QWExdks3UGdOVGViclAzTTVPNWtldzMwczlCT2NpejZLVSs0U1NjQS9DaU9rU2pRT0pFK21kanl3Y0N5WUF0eTA0R0xHVDR0MTBNd2dGRUx5Z1QrZ0V1NkpMMS9jOWttNlBveEpWZXY5bGcxZXAreDN4TVBocGlVNGpIZ2RvL09B",
    paragrafi2: "Lloji i pajisjes:",
    header2: "SMARTWATCH",
    paragrafi3: "Sisteme operative te pajtueshme:",
    header3: "-",
    paragrafi3: "Sensori i rrahjeve te zemres:",
    header4: "po",
    paragrafi4: "etegjatesia e baterise:",
    header5: "288 ore",
    paragrafi5: "32",
    header6: "E rekomanduar 39.99 €",
    header7: "34,99 €",
    link1: "Informacion mbi: Financimi, Cmimi, Sasia, Koha e dorezimit dhe Marrja",
    paragrafi6: "Eko-kontributi i TVSH dhe WEEE i perfshire",
    header8: {header: "Ofrohet dorezimi", span: "+2,99 €"},
    paragrafi7: "Dorezimi i parashikuar 21.08.2024 - 23.08.2024(Ne shporte, shkruani kodin postar dhe do te keni nje date me te sakte)",
    header9: "Koleksioni FALAS ne dyqan",
    paragrafi8: {paragraf: "Kontrolloni koleksionin ne dyqan", span: "Zgjidh Dyqanin >"},
    butoni: "Shto ne Shporte",

}
];