// export const sliderTelefonat = [
//     {
//         id: 0,
//         header1: "Top shites",
//         img: "https://images.samsung.com/is/image/samsung/p6pim/al/sm-f741bzsgeuc/gallery/al-galaxy-zflip6-f741-sm-f741bzsgeuc-542935364?$684_547_JPG$",
//         imgRating: "./images/rating-35.png",
//         paragrafi1: "200",
//         paragrafi2: "APPLE AirPods Gjenerata e 2-të me kuti karikimi (modeli 2019)",
//         paragrafi3: {paragrafi: "Rekomanduar €979", span: "799,-€"},
//         linku: "Informacion mbi: Financimi, Cmimi, Sasia, Koha e dorezimit dheMarrja",
//         paragrafi4: "Eko-kontributi i TVSH dhe WEEE i perfshire",
//     },
//     {
//         id: 1,
//         header1: "Top shites",
//         img: "https://images.samsung.com/is/image/samsung/p6pim/al/sm-f741bzsgeuc/gallery/al-galaxy-zflip6-f741-sm-f741bzsgeuc-542935364?$684_547_JPG$",
//         imgRating: "./images/rating-35.png",
//         paragrafi1: "200",
//         paragrafi2: "APPLE AirPods Gjenerata e 2-të me kuti karikimi (modeli 2019)",
//         paragrafi3: {paragrafi: "Rekomanduar €979", span: "799,-€"},
//         linku: "Informacion mbi: Financimi, Cmimi, Sasia, Koha e dorezimit dheMarrja",
//         paragrafi4: "Eko-kontributi i TVSH dhe WEEE i perfshire",
//     },
//     {
//         id: 2,
//         header1: "Top shites",
//         img: "https://images.samsung.com/is/image/samsung/p6pim/al/sm-f741bzsgeuc/gallery/al-galaxy-zflip6-f741-sm-f741bzsgeuc-542935364?$684_547_JPG$",
//         imgRating: "./images/rating-35.png",
//         paragrafi1: "200",
//         paragrafi2: "APPLE AirPods Gjenerata e 2-të me kuti karikimi (modeli 2019)",
//         paragrafi3: {paragrafi: "Rekomanduar €979", span: "799,-€"},
//         linku: "Informacion mbi: Financimi, Cmimi, Sasia, Koha e dorezimit dheMarrja",
//         paragrafi4: "Eko-kontributi i TVSH dhe WEEE i perfshire",
//     },
//     {
//         id: 3,
//         header1: "Top shites",
//         img: "https://images.samsung.com/is/image/samsung/p6pim/al/sm-f741bzsgeuc/gallery/al-galaxy-zflip6-f741-sm-f741bzsgeuc-542935364?$684_547_JPG$",
//         imgRating: "./images/rating-35.png",
//         paragrafi1: "200",
//         paragrafi2: "APPLE AirPods Gjenerata e 2-të me kuti karikimi (modeli 2019)",
//         paragrafi3: {paragrafi: "Rekomanduar €979", span: "799,-€"},
//         linku: "Informacion mbi: Financimi, Cmimi, Sasia, Koha e dorezimit dheMarrja",
//         paragrafi4: "Eko-kontributi i TVSH dhe WEEE i perfshire",
//     },
//     {
//         id: 4,
//         header1: "Top shites",
//         img: "https://images.samsung.com/is/image/samsung/p6pim/al/sm-f741bzsgeuc/gallery/al-galaxy-zflip6-f741-sm-f741bzsgeuc-542935364?$684_547_JPG$",
//         imgRating: "./images/rating-35.png",
//         paragrafi1: "200",
//         paragrafi2: "APPLE AirPods Gjenerata e 2-të me kuti karikimi (modeli 2019)",
//         paragrafi3: {paragrafi: "Rekomanduar €979", span: "799,-€"},
//         linku: "Informacion mbi: Financimi, Cmimi, Sasia, Koha e dorezimit dheMarrja",
//         paragrafi4: "Eko-kontributi i TVSH dhe WEEE i perfshire",
//     },
//     {
//         id: 5,
//         header1: "Top shites",
//         img: "https://images.samsung.com/is/image/samsung/p6pim/al/sm-f741bzsgeuc/gallery/al-galaxy-zflip6-f741-sm-f741bzsgeuc-542935364?$684_547_JPG$",
//         imgRating: "./images/rating-35.png",
//         paragrafi1: "200",
//         paragrafi2: "APPLE AirPods Gjenerata e 2-të me kuti karikimi (modeli 2019)",
//         paragrafi3: {paragrafi: "Rekomanduar €979", span: "799,-€"},
//         linku: "Informacion mbi: Financimi, Cmimi, Sasia, Koha e dorezimit dheMarrja",
//         paragrafi4: "Eko-kontributi i TVSH dhe WEEE i perfshire",
//     },
//     {
//         id: 6,
//         header1: "Top shites",
//         img: "https://images.samsung.com/is/image/samsung/p6pim/al/sm-f741bzsgeuc/gallery/al-galaxy-zflip6-f741-sm-f741bzsgeuc-542935364?$684_547_JPG$",
//         imgRating: "./images/rating-35.png",
//         paragrafi1: "200",
//         paragrafi2: "APPLE AirPods Gjenerata e 2-të me kuti karikimi (modeli 2019)",
//         paragrafi3: {paragrafi: "Rekomanduar €979", span: "799,-€"},
//         linku: "Informacion mbi: Financimi, Cmimi, Sasia, Koha e dorezimit dheMarrja",
//         paragrafi4: "Eko-kontributi i TVSH dhe WEEE i perfshire",
//     },
//     {
//         id: 7,
//         header1: "Top shites",
//         img: "https://images.samsung.com/is/image/samsung/p6pim/al/sm-f741bzsgeuc/gallery/al-galaxy-zflip6-f741-sm-f741bzsgeuc-542935364?$684_547_JPG$",
//         imgRating: "./images/rating-35.png",
//         paragrafi1: "200",
//         paragrafi2: "APPLE AirPods Gjenerata e 2-të me kuti karikimi (modeli 2019)",
//         paragrafi3: {paragrafi: "Rekomanduar €979", span: "799,-€"},
//         linku: "Informacion mbi: Financimi, Cmimi, Sasia, Koha e dorezimit dheMarrja",
//         paragrafi4: "Eko-kontributi i TVSH dhe WEEE i perfshire",
//     }
// ]